name: budgetapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  auto_route: ^7.8.0
  derry: ^1.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed: ^2.4.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

scripts:
  build: dart run build_runner build --delete-conflicting-outputs