name: budgetapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  connectivity_plus: ^5.0.1
  dartz: ^0.10.1
  derry: ^1.5.0
  dio: ^5.4.0
  expressions: ^0.2.5+1
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.3.8
  intl: ^0.18.1
  riverpod_annotation: ^2.3.4
  riverpod_lint: ^2.3.10
  shimmer: ^3.0.0

dev_dependencies:
  custom_lint: ^0.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/data/transaction.json

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-MediumItalic.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
        - asset: assets/fonts/RobotoCondensed-BoldItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
        - asset: assets/fonts/RobotoCondensed-Light.ttf
        - asset: assets/fonts/RobotoCondensed-LightItalic.ttf
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-Regular.ttf

scripts:
  watch: dart run build_runner build --delete-conflicting-outputs
